python train.py \
--experiment_name 'train_register' \
--model_type 'model_reg' \
--dataset 'CardiacSPECT_Reg' \
--data_root '../../Data/Processed_2022x01x21_1_400Train_demo/' \
--net_G 'DuRegister_DuSE' \
--net_filter 32 \
--lr 5e-5 \
--step_size 1 \
--gamma 0.99 \
--n_epochs 400 \
--batch_size 4 \
--n_patch_train 1 \
--patch_size_train 80 80 40 \
--n_patch_test 1 \
--patch_size_test 80 80 40 \
--n_patch_valid 1 \
--patch_size_valid 80 80 40 \
--eval_epochs 5 \
--snapshot_epochs 5 \
--gpu_ids 1